name: "🚀 Feature request"
about: Suggest an idea for this project
labels: enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: Describe the problem you are facing.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like.

